homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:homepage }

cv:
    path:     /cv
    defaults: { _controller: AppBundle:Default:cv }

travels:
    path:     /voyages
    defaults: { _controller: AppBundle:Default:travels }

blog:
    path:     /blog
    defaults: { _controller: AppBundle:Blog:blogDashboard }

blog_article:
    path:     /blog/{slug}
    defaults: { _controller: AppBundle:Blog:blogArticle }

travel:
    path:     /voyages/{nameTravel}
    defaults: { _controller: AppBundle:Default:travel }

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Default:contact }

send_email:
    path:     /contact/send
    defaults: { _controller: AppBundle:Default:sendEmail }
